// The vendored LiteLLM price snapshot — shape + typed accessor.
//
// `model_prices_and_context_window.json` (~1.4 MB upstream) is the source of
// truth for per-token model pricing. We vendor a Claude-only slice of it
// (`snapshot.json`, regenerated by `scripts/refresh-pricing.ts`) so the engine
// can price tokens natively without a runtime fetch — E11 adds an optional
// runtime refresh on top of this baseline.
//
// Only the four unit-price fields the cost math needs are kept per model,
// plus `cache_creation_input_token_cost_above_1hr` — retained verbatim from
// upstream for a possible future tiered-pricing mode, even though `computeCost`
// deliberately never reads it (the flat rate is the parity contract; see the
// `compute-cost.ts` doc comment).

// One model's pricing entry, as filtered into the vendored snapshot. All
// fields are USD-per-token. `cache_creation_input_token_cost_above_1hr` is
// kept for future tiered pricing but is not consumed by `computeCost`.
export type ModelPricing = {
  input_cost_per_token?: number;
  output_cost_per_token?: number;
  cache_creation_input_token_cost?: number;
  cache_read_input_token_cost?: number;
  // Upstream LiteLLM's time-tiered cache-creation rate. Retained verbatim,
  // intentionally unused — cache-creation tokens are priced flat.
  cache_creation_input_token_cost_above_1hr?: number;
};

// The vendored snapshot's top-level shape: an embedded capture timestamp plus
// the model → pricing map. `capturedAt` is stamped by the refresh script (and
// by E11's runtime fetch, from its own fetch time) and rides the live status as
// `pricing.capturedAt` — the age of the prices actually in use, which is what
// ADR-0053's provenance row reports.
export type PricingSnapshot = {
  // ISO 8601 timestamp of when the refresh script fetched upstream.
  capturedAt: string;
  // Keyed by the exact upstream LiteLLM model key (also the JSONL model string
  // for current Claude Code models, e.g. `claude-opus-4-7`).
  models: Record<string, ModelPricing>;
};
